---
title: "shiny app presentation"
author: "Sanaz Dehghani"
date: "7/6/2021"
output:
  slidy_presentation: default
  beamer_presentation: default
  ioslides_presentation: default
---
***
In this presentation we aim to present the shiny App explanation.
In this application we want to interact the data for having relationship betweenlife expectancy and continent.
***
Serverside code

Here is serverside codes.


library(plotly)
library(ggplot2)
library(gapminder)
library(shinycustomloader)

server <- function(input, output) {
    filtered_data <- reactive({
        data <- gapminder
        data <- subset(
            data,
            lifeExp >= input$life[1] & lifeExp <= input$life[2]
        )
        if (input$continent != "All") {
            data <- subset(
                data,
                continent == input$continent
            )
        }
        data
    })
    
    
    output$download_data <- downloadHandler(
        filename = function() {
            paste("gapminder-data-", Sys.Date(), ".csv", sep="")
        },
        content = function(file) {
            write.csv(filtered_data(), file)
        }
    )
    
    
    output$plot <- renderPlotly({
        
        ggplotly({
            data <- filtered_data()
            
            p <- ggplot(data, aes(gdpPercap, lifeExp)) +
                geom_point(size = 2) +
                scale_x_log10() +
                ggtitle("GDP vs Life expectancy")
              
            p
        })
    })
}

***

Input

Here we have the codes for input side bar. we have a drop down list for choosing continent and a slider Pnael for defining the expectancy range.



ui <- fluidPage(
    
    titlePanel("Shiny Application for Interacting Gapminder Data"),
    
 sidebarLayout(
        
        sidebarPanel(
            
            selectInput("continent", "Continent",
                        choices = c("All", levels(gapminder$continent))),
        
            sliderInput(inputId = "life", label = "Life expectancy",
                        min = 0, max = 120,
                        value = c(30, 50)),
        ),
 ***       

Output

Output in the main panel is an interactive plotly plot.

 mainPanel(
            
             withLoader(plotlyOutput("plot")) ),
                        
            )
        )
***

 Thanks for reviewing my assignments.